.common_only: &common_only
  stage: test
  before_script:
    - apt-get update && apt-get install -y wget tar
    - wget https://github.com/casey/just/releases/download/1.55.1/just-1.55.1-x86_64-unknown-linux-musl.tar.gz -P /tmp
    - tar -xvf /tmp/just-1.55.1-x86_64-unknown-linux-musl.tar.gz -C /tmp/
    - mv /tmp/just /usr/bin/

stages:
  - test
  - deploy_docs

image: debian:bookworm
variables:
  DEBIAN_FRONTEND: noninteractive
  SCALENODE_RAM: 4096
  SCALENODE_CPU: 1
  SCALENODE_DISK: 5

lint:
  stage: test
  <<: *common_only
  script:
    - just install-debian-deps
    - just test-lint

test_kpm_server:
  <<: *common_only
  variables:
    SCALENODE_RAM: 8192
    SCALENODE_DISK: 10
  script:
    - just install-debian-deps
    - just test-kpm-server

test_python:
  <<: *common_only
  parallel: ["3.10", "3.11", "3.12", "3.13"]
  variables:
    SCALENODE_RAM: 8192
    SCALENODE_CPU: 2
    SCALENODE_DISK: 10
    SCALENODE_FEATURES: "ryzen" # We need high IPC and frequency for the roundtrip test
  script:
    - just install-debian-deps
    - if [[ ${CI_PARALLEL_NAME} == "3.10" ]];then just test; else just test ${CI_PARALLEL_NAME}; fi

package_test:
  <<: *common_only
  variables:
    SCALENODE_CPU: 2
    SCALENODE_RAM: 8192
  script:
    - just install-debian-deps
    - just build

examples:
  <<: *common_only
  script:
    - just install-debian-deps
    - just examples
  artifacts:
    paths:
      - examples/**/build

package_cores:
  <<: *common_only
  variables:
    SCALENODE_CPU: 4
    SCALENODE_RAM: 32768
  script:
    - just install-debian-deps
    - just package
    - tar -cf build/cores_export.tar -C build/export .
  artifacts:
    paths:
      - build/cores_export.tar

pyright_check:
  <<: *common_only
  variables:
    SCALENODE_RAM: 8192
  script:
    - just install-debian-deps
    - just pyright
  allow_failure: true

build_docs:
  <<: *common_only
  variables:
    SCALENODE_RAM: 18432
    SCALENODE_CPU: 5
    SCALENODE_DISK: 20
  script:
    - just install-debian-deps --docs
    - just docs
    - tar cf "$CI_DOCS_ARCHIVE" -C docs/build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

deploy_docs:
  <<: *common_only
  stage: deploy_docs
  variables:
    GIT_STRATEGY: none
    SCALENODE_RAM: 2048
  dependencies: [build_docs]
  tags: [docs]
  script: echo 'Deploying docs'
  artifacts:
    paths: [$CI_DOCS_ARCHIVE]

include:
  - project: 'repositories/topwrap'
    ref: internal_ci_yaml
    file: 'internal.yml'
