design:
  interfaces:
    axi_bridge:
      s_axi: [ps7, M_AXI_GP0]
    litex_pwm_top:
      s_axi: [axi_bridge, m_axi]
  parameters:
    axi_bridge:
      ADDR_WIDTH: 32
      AXIL_DATA_WIDTH: 32
      AXIL_STRB_WIDTH: AXIL_DATA_WIDTH/8
      AXI_DATA_WIDTH: 32
      AXI_ID_WIDTH: 12
      AXI_STRB_WIDTH: AXI_DATA_WIDTH/8
  ports:
    axi_bridge:
      clk: [ps7, FCLK0]
      rst: [ps7, FCLK_RESET0_N]
    litex_pwm_top:
      pwm: pwm
      sys_clk: [ps7, FCLK0]
      sys_rst: [ps7, FCLK_RESET0_N]
    ps7:
      MAXIGP0ACLK: [ps7, FCLK0]
external:
  ports:
    out:
    - pwm
ips:
  axi_bridge:
    file: repo[builtin]:cores/axi_axil_adapter/core.yaml
  litex_pwm_top:
    file: file:ipcores/litex_pwm.yaml
  ps7:
    file: file:ipcores/ps7.yaml
