# Copyright (c) 2021-2026 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0
import logging
from dataclasses import dataclass
from os import cpu_count
from pathlib import Path
from typing import Any, Collection, Optional, Union

import topwrap.fuse_schema as schema
from topwrap.model.misc import Identifier
from topwrap.util import path_relative_to

logger = logging.getLogger(__name__)

CORE_FILE_DESCRIPTION = "Core file generated by TopWrap"


class SourceFile:
    def __init__(self, filename: Path, type: str):
        self.filename = filename
        self.type = type


class IP:
    def __init__(self, name: str, vlnv: str):
        """Create a new IP instance representation

        :param name: name of the instance
        :param vlnv: Version-Library-Name-Version string which represents
            specific IP Core implementation
        """
        self.name = name
        self.vlnv = vlnv


@dataclass
class FuseSocHook:
    type: str
    scripts: list[str]


class FuseSocFlowApi:
    def __init__(
        self, type: str, options: dict[str, Any], make_options: Optional[list[str]] = None
    ):
        self.type = type
        self.options = options
        self.make_options = [] if make_options is None else make_options


class FuseSocToolApi:
    def __init__(self, default_tool: str, tools: Optional[dict[str, Any]] = None):
        self.default_tool = default_tool
        self.tools = {} if tools is None else tools


class FuseSocTarget:
    def __init__(
        self,
        name: str,
        toplevel: str,
        api: Union[FuseSocToolApi, FuseSocFlowApi],
        /,
        filesets: Optional[list[str]] = None,
        hooks: Optional[list[FuseSocHook]] = None,
    ):
        self.name = name
        self.toplevel = toplevel
        self.filesets = filesets or []
        self.hooks = hooks or []
        self.api = api

    def to_schema(self) -> schema.Target:
        if isinstance(self.api, FuseSocToolApi):
            return schema.ToolTarget(
                filesets=self.filesets,
                toplevel=self.toplevel,
                hooks={hook.type: hook.scripts for hook in self.hooks},
                default_tool=self.api.default_tool,
                tools=self.api.tools,
            )

        options = self.api.options
        if self.api.make_options:
            options["flow_make_options"] = self.api.make_options

        return schema.FlowTarget(
            filesets=self.filesets,
            toplevel=self.toplevel,
            hooks={hook.type: hook.scripts for hook in self.hooks},
            flow=self.api.type,
            flow_options=options,
        )


class FuseSocBuilder:
    """Use this class to generate a FuseSoc .core file"""

    def __init__(self, part: Optional[str]):
        self.sources: list[SourceFile] = []
        self.dependencies: list[Identifier] = []
        self.external_ips = []
        self.part = part

        self.targets: dict[str, schema.Target] = {}
        self.scripts: dict[str, schema.Script] = {}
        self.filesets: dict[str, schema.FileSet] = {}
        self._generate_default_vivado = True

    def set_generate_vivado(self, generate_vivado: bool):
        self._generate_default_vivado = generate_vivado

    def add_source(self, filename: Path, type: str):
        """Adds an HDL source to the list of sources in the core file"""
        self.sources.append(SourceFile(filename, type))

    def add_target(self, target: FuseSocTarget):
        """Add a named fusesoc target"""
        self.targets[target.name] = target.to_schema()

    def add_script(self, name: str, args: list[str]):
        """Add a named fusesoc script"""
        self.scripts[name] = schema.Script(
            cmd=args,
        )

    def add_fileset(self, name: str, files: list[SourceFile], depends: list[Identifier]):
        """Add a complete fileset to the core file"""
        self.filesets[name] = schema.FileSet(
            files=[
                schema.FileSource(name=str(file.filename), file_type=file.type) for file in files
            ],
            depend=[
                schema.VLNV_S(
                    vendor=dep.vendor,
                    library=dep.library,
                    name=dep.name,
                    version=dep.version,
                )
                for dep in depends
            ],
        )

    def add_sources_dir(self, sources_dir: Collection[Path], core_path: Path):
        """Given a name of a directory, add all files found inside it.
        Recognize VHDL, Verilog, and XDC files.
        """
        for dir in sources_dir:
            for f in dir.glob("**/*"):
                suf = f.suffix.lower()
                if suf in [".vhd", ".vhdl"]:
                    f_type = "vhdlSource"
                elif suf == ".v":
                    f_type = "verilogSource"
                elif suf == ".sv":
                    f_type = "systemVerilogSource"
                elif suf == ".xdc":
                    f_type = "xdc"
                else:
                    continue

                self.add_source(path_relative_to(f, core_path.parent), f_type)

    def add_dependency(self, dependency: str | Identifier):
        """Adds a dependency to the list of dependencies in the core file"""
        if isinstance(dependency, Identifier):
            self.dependencies.append(dependency)
        else:
            vlnv_parsed = Identifier.parse_vlnv(dependency)
            self.dependencies.append(vlnv_parsed)

    def add_external_ip(self, vlnv: str, name: str):
        """Store information about IP Cores from Vivado library
        to generate hooks that will add the IPs in a TCL script.
        """
        self.external_ips.append(IP(name, vlnv))

    def build(
        self,
        top_name: str,
        core_path: Path,
        sources_dir: Collection[Path] = [],
    ):
        """Generate the final create .core file

        :param sources_dir: additional directory with source files to add
        :param template_name: name of jinja2 template to be used,
            either in working directory, or bundled with the package.
            defaults to a bundled template
        """
        if sources_dir:
            self.add_sources_dir(sources_dir, core_path)
        jobs = cpu_count() or 4

        # Generate the default rtl set
        self.add_fileset("rtl", self.sources, self.dependencies)

        if self._generate_default_vivado:
            self.add_target(
                FuseSocTarget(
                    "default",
                    top_name,
                    FuseSocToolApi(
                        default_tool="vivado",
                        tools={"vivado": {"part": self.part} if self.part is not None else {}},
                    ),
                    filesets=["rtl"],
                    hooks=[FuseSocHook("pre_build", ["set_jobs"])],
                )
            )

            self.add_script(
                "set_jobs",
                [
                    "sed",
                    "-i",
                    f'"s/launch_runs synth_1/launch_runs synth_1 -jobs {jobs}/g"',
                    f"{top_name}_0_synth.tcl",
                ],
            )

        text = schema.Core(
            name=schema.VLNV_S("", "", top_name, ""),
            description=CORE_FILE_DESCRIPTION,
            filesets=self.filesets,
            targets=self.targets,
            scripts=self.scripts,
        ).to_yaml()
        with open(core_path, "w") as f:
            f.write(text)
