from examples.ir_examples.SoC_AXI.ir.design import top as axi_soc_top
from topwrap.backend.sv.backend import SystemVerilogBackend
from topwrap.frontend.sv.frontend import SystemVerilogFrontend


class TestAxiGenerator:
    ports = [
        "i_inst_simple_manager_bus_awid",
        "i_inst_simple_manager_bus_awaddr",
        "i_inst_simple_manager_bus_awlen",
        "i_inst_simple_manager_bus_awsize",
        "i_inst_simple_manager_bus_awburst",
        "i_inst_simple_manager_bus_awlock",
        "i_inst_simple_manager_bus_awcache",
        "i_inst_simple_manager_bus_awprot",
        "i_inst_simple_manager_bus_awregion",
        "i_inst_simple_manager_bus_awqos",
        "i_inst_simple_manager_bus_awvalid",
        "o_inst_simple_manager_bus_awready",
        "i_inst_simple_manager_bus_arid",
        "i_inst_simple_manager_bus_araddr",
        "i_inst_simple_manager_bus_arlen",
        "i_inst_simple_manager_bus_arsize",
        "i_inst_simple_manager_bus_arburst",
        "i_inst_simple_manager_bus_arlock",
        "i_inst_simple_manager_bus_arcache",
        "i_inst_simple_manager_bus_arprot",
        "i_inst_simple_manager_bus_arregion",
        "i_inst_simple_manager_bus_arqos",
        "i_inst_simple_manager_bus_arvalid",
        "o_inst_simple_manager_bus_arready",
        "i_inst_simple_manager_bus_wdata",
        "i_inst_simple_manager_bus_wstrb",
        "i_inst_simple_manager_bus_wlast",
        "i_inst_simple_manager_bus_wvalid",
        "o_inst_simple_manager_bus_wready",
        "o_inst_simple_manager_bus_bid",
        "o_inst_simple_manager_bus_bresp",
        "o_inst_simple_manager_bus_bvalid",
        "i_inst_simple_manager_bus_bready",
        "o_inst_simple_manager_bus_rid",
        "o_inst_simple_manager_bus_rdata",
        "o_inst_simple_manager_bus_rresp",
        "o_inst_simple_manager_bus_rlast",
        "o_inst_simple_manager_bus_rvalid",
        "i_inst_simple_manager_bus_rready",
        "o_uart0_bus_awid",
        "o_uart0_bus_awaddr",
        "o_uart0_bus_awlen",
        "o_uart0_bus_awsize",
        "o_uart0_bus_awburst",
        "o_uart0_bus_awlock",
        "o_uart0_bus_awcache",
        "o_uart0_bus_awprot",
        "o_uart0_bus_awregion",
        "o_uart0_bus_awqos",
        "o_uart0_bus_awvalid",
        "i_uart0_bus_awready",
        "o_uart0_bus_arid",
        "o_uart0_bus_araddr",
        "o_uart0_bus_arlen",
        "o_uart0_bus_arsize",
        "o_uart0_bus_arburst",
        "o_uart0_bus_arlock",
        "o_uart0_bus_arcache",
        "o_uart0_bus_arprot",
        "o_uart0_bus_arregion",
        "o_uart0_bus_arqos",
        "o_uart0_bus_arvalid",
        "i_uart0_bus_arready",
        "o_uart0_bus_wdata",
        "o_uart0_bus_wstrb",
        "o_uart0_bus_wlast",
        "o_uart0_bus_wvalid",
        "i_uart0_bus_wready",
        "i_uart0_bus_bid",
        "i_uart0_bus_bresp",
        "i_uart0_bus_bvalid",
        "o_uart0_bus_bready",
        "i_uart0_bus_rid",
        "i_uart0_bus_rdata",
        "i_uart0_bus_rresp",
        "i_uart0_bus_rlast",
        "i_uart0_bus_rvalid",
        "o_uart0_bus_rready",
        "o_uart1_bus_awid",
        "o_uart1_bus_awaddr",
        "o_uart1_bus_awlen",
        "o_uart1_bus_awsize",
        "o_uart1_bus_awburst",
        "o_uart1_bus_awlock",
        "o_uart1_bus_awcache",
        "o_uart1_bus_awprot",
        "o_uart1_bus_awregion",
        "o_uart1_bus_awqos",
        "o_uart1_bus_awvalid",
        "i_uart1_bus_awready",
        "o_uart1_bus_arid",
        "o_uart1_bus_araddr",
        "o_uart1_bus_arlen",
        "o_uart1_bus_arsize",
        "o_uart1_bus_arburst",
        "o_uart1_bus_arlock",
        "o_uart1_bus_arcache",
        "o_uart1_bus_arprot",
        "o_uart1_bus_arregion",
        "o_uart1_bus_arqos",
        "o_uart1_bus_arvalid",
        "i_uart1_bus_arready",
        "o_uart1_bus_wdata",
        "o_uart1_bus_wstrb",
        "o_uart1_bus_wlast",
        "o_uart1_bus_wvalid",
        "i_uart1_bus_wready",
        "i_uart1_bus_bid",
        "i_uart1_bus_bresp",
        "i_uart1_bus_bvalid",
        "o_uart1_bus_bready",
        "i_uart1_bus_rid",
        "i_uart1_bus_rdata",
        "i_uart1_bus_rresp",
        "i_uart1_bus_rlast",
        "i_uart1_bus_rvalid",
        "o_uart1_bus_rready",
    ]

    def test_parsing(self):
        back = SystemVerilogBackend(all_pins=True, desc_comms=True, mod_stubs=True)
        [out] = back.serialize(back.represent(axi_soc_top), combine=True)
        front = SystemVerilogFrontend()
        modules = front.parse_str([out.content]).modules
        interconnect_module = modules[-1]
        for port in self.ports:
            interconnect_module.ports.find_by_name_or_error(port)
