# Copyright (c) 2025 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

import re

from topwrap.model.hdl_types import Bit
from topwrap.model.interface import (
    InterfaceDefinition,
    InterfaceMode,
    InterfaceSignal,
    InterfaceSignalConfiguration,
)
from topwrap.model.misc import Identifier

from .util import IN, OUT, sig

ahblite_intf = InterfaceDefinition(
    id=Identifier(name="AHBLite"),
    signals=[
        sig("haddr", "haddr", 64, OUT),
        sig("hwdata", "hwdata", 32, OUT),
        sig("hrdata", "hrdata", 32, IN),
        sig("hsel", "hsel", 1, OUT, mreq=False, default="1"),
        sig("hwrite", "hwrite", 1, OUT),
        sig("htrans", "htrans", 1, OUT),
        sig("hsize", "hsize", 3, OUT),
        sig("hresp", "hresp", 1, IN),
        InterfaceSignal(
            name="hready",
            regexp=re.compile("hready"),
            type=Bit(),
            # The AHB specification specifies that HREADY is an input to both the manager and
            # subordinate, and is instead generated by the multiplexor (or interconnect as a whole)
            # based on HREADYOUT signals coming from subordinates.
            modes={
                InterfaceMode.MANAGER: InterfaceSignalConfiguration(direction=IN, required=False),
                InterfaceMode.SUBORDINATE: InterfaceSignalConfiguration(
                    direction=IN, required=False
                ),
            },
        ),
        sig("hreadyout", "hreadyout", 1, IN, mreq=False, sreq=True),
    ],
)
