# Copyright (c) 2021-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

name: Release creation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 23 * * SUN'

jobs:
  release-creation:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Install just
        run: |
          apt-get update && apt-get install -y git wget tar
          wget https://github.com/casey/just/releases/download/1.55.1/just-1.55.1-x86_64-unknown-linux-musl.tar.gz -P /tmp
          tar -xvf /tmp/just-1.55.1-x86_64-unknown-linux-musl.tar.gz -C /tmp/
          mv /tmp/just /usr/bin/

      - uses: actions/checkout@v4

      - name: Build packages
        run: |
          just install-debian-deps
          just build

      - name: Build package cores
        run: |
          just package
          tar -cf build/cores_export.tar -C build/export .

      - name: Publish or update the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: topwrap
          body: Built from ${{ github.sha }}
          fail_on_unmatched_files: true
          make_latest: true
          files: |
            dist/topwrap*.tar.gz
            build/cores_export.tar
